export const ADD_TO_CART = 'cart/add_cart'
export const REMOVE_CART = 'cart/remove_cart'
export const INCREMENT = 'cart/increment'
export const DECREMENT = 'cart/decrement'
export const TOTAL_PRICE = 'cart/totalPrice'